# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "capistrano", "~>2.0"
gem "colored", "~>1.2"

gem "minitest", "~>4.7", :group => [:development, :test]
gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe", "~>3.5", :group => [:development, :test]

# vim: syntax=ruby
